spring:
  mysql:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bugtracker?autoReconnect=true
    username: mantisbt
    password: mantisbt

  # 설정들은 spring.io에서 doc에서 찾아서 공부해야한다.
  # jpa설정
  jpa:
    hibernate: # hibernate 사용 설정
      # 애플리케이션 실행 시점에 테이블을 다 지우고, 내가 가진 entity 정보를 보고 다시 테이블 자동 생성
      # if exists drop table 해주고 다시 만들어준다고 보면 된다. (create 를 하면 테이블을 자동으로 생성)
      ddl-auto: create
    generate-ddl: true
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true
        show_sql: true
        use_sql_comments: true # 추가적인 주석표시 설정

# 로그 레벨 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # ? 파라미터(실제 들어가는 파라미터값 찍어주는 설정)
        SQL: debug
